export const SAVE_FOR_LATER_ADD_ITEM = 'SAVE_FOR_LATER_ADD_ITEM';
export const SAVE_FOR_LATER_REMOVE_ITEM = 'SAVE_FOR_LATER_REMOVE_ITEM';
export const SAVE_FOR_LATER_CLEAR_ITEMS = 'SAVE_FOR_LATER_CLEAR_ITEMS';
